image:
  repository: gitea/gitea
  tag: 1.22.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: traefik
  host: gitea.homelab.example.com
  annotations:
    cert-manager.io/cluster-issuer: step-ca-issuer
  tls:
    enabled: true
    secretName: gitea-tls

gitea:
  # aktuell nur als Platzhalter – kann später für einen Bootstrap-Job genutzt werden
  admin:
    username: ""
    password: ""
    email: ""

  # App-Settings
  secretKey: change-me
  disableInstallPage: true

persistence:
  enabled: true
  storageClassName: local-path
  size: 10Gi
  accessModes:
    - ReadWriteOnce

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
